include:
  - proxy.yaml

services:
  # 3.1. web
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=virtd
    depends_on:
      db:
        condition: service_healthy

  # 3.2. db
  db:
    image: mysql:8
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=very_strong
      - MYSQL_DATABASE=virtd
      - MYSQL_USER=app
      - MYSQL_PASSWORD=very_strong
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$DB_PASSWORD"]
      interval: 3s
      timeout: 3s
      retries: 5